ticket_to_culture/forum/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static

# from ticket_to_culture.ticket_to_culture import settings

from . import views

app_name = 'forum'
urlpatterns = [
    path('', views.discovery_page, name='discoveryPage'),
    path('signin/', views.signin, name='signin'),
    path('signup/', views.signup, name='signup'),
    path('signout/', LogoutView.as_view(), name='signout'),
    path('profile/', views.profile_page, name='profile'),
    path('createPost/', views.create_post, name='createPost'),
    path('my-posts/', views.my_posts, name='myPosts'),
    path('my-posts/sell/<int:sold_id>/', views.sell_post, name='sellPost'),
    path('my-posts/undo-sold/<int:sold_id>/', views.undo_sold, name='undoSoldPost'),
    path('rate-buyer-search/<int:sold_id>/', views.rate_buyer_search, name='rateBuyerSearch'),
    path('rate-buyer/<int:sold_id>/<int:buyer_id>/', views.rate_buyer, name='rateBuyer'),
    path('rate-seller/<int:seller_rating_id>/', views.rate_seller, name='rateSeller'),
    path('post/<int:post_id>', views.post, name = 'post'),
    path('change-password/', views.change_password, name='changePassword'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ticket_to_culture/ticket_to_culture/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('forum.urls')),
    path('admin/', admin.site.urls),
]

ticket_to_culture/forum/forms.py
from dataclasses import field
from email.policy import default
from logging import Filter
from webbrowser import BackgroundBrowser
from wsgiref import validate

from .models import Profile
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Post
from django.core.validators import RegexValidator

LOCATION_CHOICES= [
    ('lokasjon', 'Lokasjon'),
    ('bergen', 'Bergen'),
    ('oslo', 'Oslo'),
    ('trondheim', 'Trondheim'),
    ('stavanger', 'Stavanger'),
    ('larvik', 'Larvik'),
    ('sandes', 'Sandes'),
    ('annet', 'Annet'),
    ]

TYPE_CHOICES= [
    ('arrangement', 'Arrangement'),
    ('konsert', 'Konsert'),
    ('teater', 'Teater'),
    ('film', 'Film'),
    ('kunst', 'Kunst'),
    ('karnival', 'Karnival'),
    ('standup', 'Standup'),
    ('annet', 'Annet'),
    ]

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=40, required=True, help_text='Påkrevd.', label="Fornavn")
    last_name = forms.CharField(max_length=40, required=True, help_text='Påkrevd.', label="Etternavn")
    email = forms.EmailField(max_length=255, help_text='Påkrevd. Skriv inn en valid epost addresse.', label="Email")
    phoneNumberRegex = RegexValidator(regex=r"^\+?1?\d{8,15}$")
    phone_number = forms.CharField(max_length=11, validators=[phoneNumberRegex], help_text="Valgfritt telefonnummer.", label="Telefonnummer")
    image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control-file'}),
                             help_text="Valgfritt profilbilde.",
                             label="Profilbilde")

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'phone_number', 'password1', 'password2',)


class CreatePostForm(forms.Form):
    # TODO: Gjøre så bruker kan laste opp bilde
    title = forms.CharField(max_length=40, required=True, help_text='En tittel for annonsen', label="Tittel")
    description = forms.CharField(widget=forms.Textarea, help_text='En beskrivelse for annonsen.', label="Beskrivelse")
    is_sale = forms.BooleanField(required=False, help_text="Er annonsen et salg?", initial=True, label="Salgs annonse")
    price = forms.DecimalField(max_digits=16, help_text='Pris for annonsen.', label="Pris")
    image = forms.ImageField(required=False, help_text="Bilde for annonse.", label="Bilde")
    location= forms.CharField(label='Lokasjon', widget=forms.Select(choices=LOCATION_CHOICES), required=True)
    type= forms.CharField(label='Arrangement', widget=forms.Select(choices=TYPE_CHOICES), required=True )
    


    class Meta:
        model = Post
        fields = ('title', 'description', 'is_sale', 'price', 'location', 'type')


class UpdateUserForm(forms.ModelForm):
    email = forms.EmailField(required=True, label="E-post",
                             widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['email']


class UpdateProfileForm(forms.ModelForm):
    image = forms.ImageField(label="Profilbilde",widget=forms.FileInput(attrs={'class': 'form-control-file'}))

    phoneNumberRegex = RegexValidator(regex=r"^\+?1?\d{8,15}$")
    phone = forms.CharField(label="Telefonnummer",max_length=11, validators=[phoneNumberRegex], required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Profile
        fields = ['image', 'phone']


class FilterPosts(forms.Form):
    priceLowHigh = forms.BooleanField(label='Lav-Høy', required=False)
    for_sale = forms.BooleanField(label='Til salgs', required=False)
    for_buy = forms.BooleanField(label='Ønskes kjøpt', required=False)
    location= forms.CharField(label='Lokasjon', widget=forms.Select(choices=LOCATION_CHOICES), required=False)
    type= forms.CharField(label='Arrangement', widget=forms.Select(choices=TYPE_CHOICES), required=False)
    
        
    class Meta:
        model = Filter
        fields = ['price', 'location', 'for_sale', 'for_buy', 'type']
        
    
    
         
       

ticket_to_culture/forum/views.py
from sre_constants import SUCCESS
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render, get_object_or_404
from django.template import loader
from django.contrib import messages
from django.contrib.auth import authenticate, login, update_session_auth_hash
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib.auth.models import User
from django.core.exceptions import SuspiciousOperation
from .models import Profile, Post, Rating
from .forms import SignUpForm, UpdateUserForm, UpdateProfileForm, CreatePostForm, FilterPosts
from ticket_to_culture.settings import MEDIA_ROOT, MEDIA_URL


@login_required
def create_post(request):
    user = request.user
    if request.method == "GET":
        form = CreatePostForm()
        return render(request, 'post/createPost.html', {'form': form})
    elif request.method == "POST":
        form = CreatePostForm(request.POST, request.FILES)
        if form.is_valid() and user.is_authenticated:
            form = form.cleaned_data
            post = Post(user=user, title=form["title"], description=form["description"], is_sale=form["is_sale"],
                        price=form["price"], image=form["image"], location=form["location"], type=form["type"])
            post.save()
            return HttpResponseRedirect(reverse('forum:myPosts'))
        return HttpResponse("ikke valid")
    


@login_required
def profile_page(request):
    if request.method == 'POST':
        user_form = UpdateUserForm(request.POST, instance=request.user)
        profile_form = UpdateProfileForm(request.POST, request.FILES, instance=request.user.profile)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            form = profile_form.save()
            form.image = profile_form.cleaned_data.get('image')
            user_form.save()
            profile_form.save()

    else:
        template = loader.get_template('user/profile.html')
        user_form = UpdateUserForm(instance=request.user)
        profile_form = UpdateProfileForm(instance=request.user.profile)
        # Calculate average score
        my_ratings = Rating.objects.filter(rated_user=request.user)
        totalScore = 0
        for r in my_ratings:
            totalScore += r.rating_value
        if len(my_ratings) == 0:
            score = "Ikke vurdert"
        else:
            score = str(round(totalScore / len(my_ratings), 2)) + "/5.0"

        # Get user info
        user = request.user
        context = {
            "image": user.profile.image,
            "username": user.username,
            "email": user.email,
            'user_form': user_form,
            'profile_form': profile_form,
            'phone': user.profile.phone,
            'score': score,
        }
        return HttpResponse(template.render(context, request))

    # Get user info
    user = request.user
    context = {
        "image": user.profile.image,
        "username": user.username,
        "email": user.email,
        'user_form': user_form,
        'profile_form': profile_form,
        'phone': user.profile.phone
    }
    return render(request, 'user/profile.html', context)


@login_required
def change_password(request):
    if request.method == 'POST':
        password_form = PasswordChangeForm(user=request.user, data=request.POST)

        if password_form.is_valid():
            password_form.save()
            update_session_auth_hash(request, password_form.user)
            return redirect('/profile')

    else:
        password_form = PasswordChangeForm(request.user)
        template = loader.get_template('user/change-password.html')
    return render(request, 'user/change-password.html', {'password_form': password_form})

# View for when seller gives rating to a buyer.
@login_required
def rate_buyer(request, sold_id, buyer_id):
    if request.method == "GET":
        return render(request, "rating/rate-buyer.html", {"sold_id": sold_id, "buyer_id": buyer_id}, )
    else:
        # Seller gives a rating to buyer:
        rate_text = request.POST["rating"]
        rating = 0
        try:
            rating = int(rate_text)
        except:
            raise SuspiciousOperation(
                "Rating value cannot be casted to an int")
        post = Post.objects.get(pk=sold_id)
        buyer = User.objects.get(pk=buyer_id)
        Rating.objects.create(rated_user=buyer, rated_by_user=post.user,
                              rating_value=rating, is_seller_rating_buyer=True, post=post)
        return redirect("forum:sellPost", sold_id)


# View for when buyer gives rating to a seller.
# @seller_rating_id is the ID for the rating the seller gave to buyer.
@login_required
def rate_seller(request, seller_rating_id):
    if request.method == "GET":
        return render(request, "rating/rate-seller.html", {"seller_rating_id": seller_rating_id}, )
    else:
        # Buyer gives a rating to buyer:
        rate_text = request.POST["rating"]
        rating = 0
        try:
            rating = int(rate_text)
        except:
            raise SuspiciousOperation(
                "Rating value cannot be casted to an int")
        # Create buyer rating in reponse to seller rating:
        seller_rating = Rating.objects.get(pk=seller_rating_id)
        seller_user = seller_rating.rated_by_user
        post = seller_rating.post
        Rating.objects.create(rated_user=seller_user, rated_by_user=request.user, rating_value=rating,
                              post=post, rated_user_responded=True, is_seller_rating_buyer=False)
        # Set responded to True on seller rating of buyer:
        seller_rating.rated_user_responded = True
        seller_rating.save()
        return redirect("forum:myPosts")


# View for searching for the buyers username, to give a rating.
@login_required
def rate_buyer_search(request, sold_id):
    print("sold_id:: " + str(sold_id))
    if request.method == "GET":
        return render(request, "rating/search.html", {"sold_id": sold_id})
    elif request.method == "POST":
        formdata = request.POST
        users = User.objects.filter(username__contains=formdata["search"])
        return render(request, "rating/search.html", {"results": users, "sold_id": sold_id})


@login_required
def my_posts(request):
    if request.method == "GET":
        template = loader.get_template('user/my-posts.html')
        # Get posts info
        user = request.user
        active_posts = Post.objects.filter(user=user).filter(is_sold=False)
        old_posts = Post.objects.filter(user=user).filter(is_sold=True)
        ratings_available = Rating.objects.filter(rated_user=user).filter(
            rated_user_responded=False).filter(is_seller_rating_buyer=True)
        context = {
            "active_posts": active_posts,
            "old_posts": old_posts,
            "ratings_available": ratings_available,
        }
        return HttpResponse(template.render(context, request))
    else:
        return HttpResponse("unknown")


@login_required
def sell_post(request, sold_id):
    post = get_object_or_404(Post, pk=sold_id)
    post.is_sold = True
    post.save()
    return redirect('forum:myPosts')


@login_required
def undo_sold(request, sold_id):
    post = get_object_or_404(Post, pk=sold_id)
    post.is_sold = False
    post.save()
    return redirect('forum:myPosts')


def signin(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                HttpResponse(f"You are now logged in as {username}.")
                return redirect("/")
            else:
                HttpResponse("Invalid username or password.")
        else:
            HttpResponse("Invalid username or password.")
    form = AuthenticationForm()
    return render(request, 'auth/signin.html', {'form': form})


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST, request.FILES or None)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()  # load the profile.html instance created by the signal
            user.profile.phone = form.cleaned_data.get('phone_number')
            user.profile.image = form.cleaned_data.get('image')
            user.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/')
    else:
        form = SignUpForm()
    return render(request, 'auth/signup.html', {'form': form})


def discovery_page(request):
    signedin = request.user.is_authenticated
    template = loader.get_template('discovery/discovery_page.html')
    post_list = Post.objects.filter(is_sold=False)
    form = FilterPosts(request.POST)
    
    if(request.method == "POST"):
        form = FilterPosts(request.POST)
        # Sorterer på pris, lav-til-høy
        if form["priceLowHigh"].value() == True:
            post_list = post_list.filter(is_sold=False).order_by('price')

        # Sorterer på om annonsen er til salgs 
        if form["for_sale"].value() == True:
            post_list = post_list.filter(is_sale=True)

        # Sorterer på om annosen ønskes kjøpt
        if form["for_buy"].value() == True:
            post_list = post_list.filter(is_sale=False)

        # Filterer på lokasjon
        if(form['location'].value() != "lokasjon"):
            by = form['location'].value()

ticket_to_culture/forum/templates/rating/rate-buyer.html
{% extends "../base.html" %} {% block content %}

<form
  action="{% url 'forum:rateBuyer' sold_id buyer_id %}"
  method="POST"
  class="form-group"
  style="
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
  "
>
  {% csrf_token %}

  <h4>Ønsker du å gi vurdering til kjøperen?</h4>

  <div
    style="
      display: flex;
      flex-direction: row;
      align-items: center;
      margin-bottom: 0.1rem;
      margin-top: 1rem;
    "
  >
    <input type="radio" id="one" name="rating" value="1" required />
    <label for="one"><h3>1</h3></label>

    <input
      type="radio"
      id="two"
      name="rating"
      value="2"
      style="margin-left: 1rem"
    />
    <label for="two"><h3>2</h3></label>

    <input
      type="radio"
      id="three"
      name="rating"
      value="3"
      style="margin-left: 1rem"
    />
    <label for="three"><h3>3</h3></label>

    <input
      type="radio"
      id="four"
      name="rating"
      value="4"
      style="margin-left: 1rem"
    />
    <label for="four"><h3>4</h3></label>

    <input
      type="radio"
      id="five"
      name="rating"
      value="5"
      style="margin-left: 1rem"
    />
    <label for="five"><h3>5</h3></label>
  </div>

  <p
    style="
      text-transform: uppercase;
      font-size: 0.75rem;
      line-height: 1rem;
      color: rgb(156 163 175);
    "
  >
    Gi en vurdering der 1 er dårligst og 5 er best.
  </p>

  <input
    type="submit"
    class="btn btn-primary"
    value="Gi vurdering"
    style="margin-top: 1rem"
  />
</form>
<form
  action="{% url 'forum:sellPost' sold_id %}"
  method="POST"
  class="form-group"
  style="display: flex; justify-content: center; align-items: center"
>
  {% csrf_token %}
  <input
    type="submit"
    class="btn btn-sm btn-danger"
    value="Ikke vurder kjøper"
  />
</form>

{% endblock content %}

ticket_to_culture/forum/templates/rating/rate-seller.html
{% extends "../base.html" %} {% block content %}

<form
  action="{% url 'forum:rateSeller' seller_rating_id %}"
  method="POST"
  class="form-group"
  style="
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
  "
>
  {% csrf_token %}

  <h4>Ønsker du å gi vurdering til selgeren?</h4>

  <div
    style="
      display: flex;
      flex-direction: row;
      align-items: center;
      margin-bottom: 0.1rem;
      margin-top: 1rem;
    "
  >
    <input type="radio" id="one" name="rating" value="1" required />
    <label for="one"><h3>1</h3></label>

    <input
      type="radio"
      id="two"
      name="rating"
      value="2"
      style="margin-left: 1rem"
    />
    <label for="two"><h3>2</h3></label>

    <input
      type="radio"
      id="three"
      name="rating"
      value="3"
      style="margin-left: 1rem"
    />
    <label for="three"><h3>3</h3></label>

    <input
      type="radio"
      id="four"
      name="rating"
      value="4"
      style="margin-left: 1rem"
    />
    <label for="four"><h3>4</h3></label>

    <input
      type="radio"
      id="five"
      name="rating"
      value="5"
      style="margin-left: 1rem"
    />
    <label for="five"><h3>5</h3></label>
  </div>

  <p
    style="
      text-transform: uppercase;
      font-size: 0.75rem;
      line-height: 1rem;
      color: rgb(156 163 175);
    "
  >
    Gi en vurdering der 1 er dårligst og 5 er best.
  </p>

  <input
    type="submit"
    class="btn btn-primary"
    value="Gi vurdering"
    style="margin-top: 1rem"
  />
</form>

{% endblock content %}

ticket_to_culture/forum/templates/rating/search.html
{% extends "../base.html" %}
{% block content %}

    <form action="{% url 'forum:rateBuyerSearch' sold_id %}" method="POST" class="form-group" style="display: flex; flex-direction: row;">
        {% csrf_token %}
        <input type="text" placeholder="Skriv brukernavnet til kjøperen" class="form-control" name="search" id="search" style="margin-right: 1rem;"/>
        <input type="submit" class="btn btn-primary" value="Søk etter bruker"/>
    </form>

    {% if results %}
        {% for r in results %}
            <div class="" style="padding: 1rem; display: flex; flex-direction: row; justify-content: space-between; align-items:center; background: #dfeaed;" >
                <h5 style="margin-bottom: 0px; padding-bottom: 0px; display: inline-block;">{{ r.username }}</h5>
                <form action="{% url 'forum:rateBuyer' sold_id r.id %}" method="GET" class="form-group" style="padding: 0; margin: 0;" >
                    {% csrf_token %}
                    <input type="submit" class="btn btn-primary" value="Velg" />
                </form>
            </div>
        {% endfor %}
    {% endif %}

{% endblock content %}